folder_location: '/hra/results/'
folder_name: 'tabular_'
file_name: 'soc_ai_list.pkl'
random_seed: 1234

head_list: ['food', 'capsule', 'ghost', 'scared_ghost', 'exploration']
learn_only_head_list: ['']

aggregator: 'posnormneg'
q_neg_weight_vec: [1.2, 1.2, 1.2, 1.2]

gvf_food_pseudo_reward: 1.0
gvf_capsule_pseudo_reward: 1000.0
gvf_ghost_pseudo_reward: 1000.0
gvf_scared_ghost_pseudo_reward: 10000.0

gvf_pseudo_negative_reward: 0.


food_env_reward: 10.
capsule_env_reward: 1.
ghost_env_reward: -450.
scared_ghost_env_reward: 200.

aggregator_epsilon: 1.0
aggregator_final_epsilon: 1.0
aggregator_decay_start: 1
aggregator_decay_steps: 1

agent_actions: ['North', 'East', 'South', 'West']

init_q: 0.0
gamma: 0.99
alpha: 0.001
final_alpha: 0.001
alpha_decay_steps: 1
alpha_decay_start: 1

learning_method: mean  # mean or max


#Diversification and Count-Based explorer heads parameters
no_of_steps_to_explore: 5
